"""add camera configurations

Revision ID: 75cc9ee7cca4
Revises: 7c06e41b48e0
Create Date: 2026-07-16 14:46:38.116618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cc9ee7cca4'
down_revision: Union[str, Sequence[str], None] = '7c06e41b48e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('stream_timeout', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('detection_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id')
    )
    op.create_index(op.f('ix_camera_configurations_id'), 'camera_configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camera_configurations_id'), table_name='camera_configurations')
    op.drop_table('camera_configurations')
    # ### end Alembic commands ###
