"""add system configuration fields

Revision ID: 7c06e41b48e0
Revises: 9d8e8f3d66d8
Create Date: 2026-07-16 13:18:02.860167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c06e41b48e0'
down_revision: Union[str, Sequence[str], None] = '9d8e8f3d66d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configurations', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('system_configurations', sa.Column('data_type', sa.String(length=50), nullable=False))
    op.add_column('system_configurations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('system_configurations', sa.Column('is_editable', sa.Boolean(), nullable=False))
    op.add_column('system_configurations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('system_configurations', 'value',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('system_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('system_configurations_key_key'), 'system_configurations', type_='unique')
    op.create_index(op.f('ix_system_configurations_category'), 'system_configurations', ['category'], unique=False)
    op.create_index(op.f('ix_system_configurations_id'), 'system_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_system_configurations_key'), 'system_configurations', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_configurations_key'), table_name='system_configurations')
    op.drop_index(op.f('ix_system_configurations_id'), table_name='system_configurations')
    op.drop_index(op.f('ix_system_configurations_category'), table_name='system_configurations')
    op.create_unique_constraint(op.f('system_configurations_key_key'), 'system_configurations', ['key'])
    op.alter_column('system_configurations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('system_configurations', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('system_configurations', 'created_at')
    op.drop_column('system_configurations', 'is_editable')
    op.drop_column('system_configurations', 'description')
    op.drop_column('system_configurations', 'data_type')
    op.drop_column('system_configurations', 'category')
    # ### end Alembic commands ###
